#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Make sure to configure!
#include "JoystickDriver.c"

task main()
{
	int THRESHOLD = 10;
	while(true) // Infinite loop:
	{
		getJoystickSettings(joystick);

		int x = joystick.joy1_x1;
		int y = joystick.joy1_y1;


		if (abs(x) > THRESHOLD || abs(y) > THRESHOLD) { //eliminates static
		  motor[motorB] = (y + x);
		  motor[motorC] = (y - x);
		} else {
		  motor[motorB] = 0;
		  motor[motorC] = 0;
		}
	};
};
